Feat: add sign up button to navbar next to sign in
Lebanon-WBC-Capstones/blood-bank-web pull request #140
Opened 2021-03-16 13:32 UTC by JanaZR9

Fixes #133

2021-03-16 14:51 UTC, wisammechano requested changes

2021-03-16 14:51 UTC, wisammechano commented on src/pages/Home.js
> +        style={{ top: '176vw' }}
@JanaZR9 please don't use absolute positioning, you can use negative margins. Also, fix the sign-in button. It has same problem

If the image is getting shifted, you can give it a negative margin on top to pull it up. Bu avoid using absolute positioning!

2021-03-18 00:12 UTC, JanaZR9 commented
It's working like I did . 
position : Relative and negative value for the top .

2021-03-18 13:30 UTC, wisammechano approved these changes

2021-03-18 13:30 UTC, merged