Feat: create the sign in component
Lebanon-WBC-Capstones/blood-bank-web pull request #31
Opened 2021-02-17 21:23 UTC by joliehobloss

Fixes #29

2021-02-18 22:08 UTC, nabigha-mogharbel reviewed
What you did is good so far. I have like small note, if you can do it ti would be great and consistent with the Sign Up form i did. the idea is if you can put max-width to the whole SignIn div by 600 px so the input wont expand like this in desktop mode.

2021-02-21 18:29 UTC, wisammechano requested changes

2021-02-21 18:29 UTC, wisammechano commented on src/App.js
> +      <SignIn />
please revert app.js and don't commit after testing.

2021-02-21 18:29 UTC, wisammechano commented on src/components/SignIn.js
> +          style={{ display: 'block', margin: '0 auto' }}
`className="block mx-auto"` use tailwind instead

2021-02-21 18:29 UTC, wisammechano commented on src/components/SignIn.js
> +    <div class="bg-transparent">
wrap the whole thing by a wrapper using the container class

https://tailwindcss.com/docs/container

2021-02-24 20:01 UTC, wisammechano approved these changes

2021-02-24 20:01 UTC, merged