layla2420/issue30
Lebanon-WBC-Capstones/blood-bank-web pull request #34
Opened 2021-02-17 23:45 UTC by layla2420

Fixes #30

2021-02-17 23:47 UTC, layla2420 commented
email configuration done

2021-02-21 18:32 UTC, wisammechano commented on src/App.js
> +import Configuration from './components/emailconfiguratin';
Please revert App.js after testing

2021-02-21 18:33 UTC, wisammechano requested changes

2021-02-21 18:33 UTC, wisammechano commented on src/App.js
> +import Configuration from './components/emailconfiguratin';
please revert App.js after testing.

2021-02-21 18:33 UTC, wisammechano commented on src/components/emailconfiguratin.js
> +const Configuration = () => {
Please rename to `Confirmation` and the file name too should be EmailConfirmation.js

2021-02-23 16:04 UTC, wisammechano commented on src/components/EmailConfirmation.js
> +export default Configuration;
I fixed this for now, but please pay attention to export correctly

2021-02-23 16:04 UTC, wisammechano approved these changes

2021-02-23 16:06 UTC, merged